url: ""
baseurl: ""
destination: _site
robots: noindex,nofollow
environment: 'development'

sass:
  style: uncompressed

defaults:
  -
    scope:
      path: "pages"
      type: pages
    values:
      locale: fr_FR
      layout: default
